apiVersion: v1
kind: ReplicationController
metadata:
  name: testwithuser6
  namespace: com-att-ocnp-mgmt
spec:
  replicas: 1
  selector:
    app: testwithuser6
  template:
    metadata:
      labels:
        app: testwithuser6
    spec:
      serviceAccount: YOUR
      containers:
      - name: testwithuser6
        image: ${docker-registry}/${docker-namespace}/testwithuser6:latest
        imagePullPolicy: Always
        ports:
         - containerPort: 8080